### ISSUE TITLE
Sharing iP code quality feedback [for @HugeNoob]

### ISSUE THREAD

**Issue by soc-se-bot-red** [HugeNoob/ip#6]
@HugeNoob We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/Duke.java` lines `51-55`](https://github.com/HugeNoob/ip/blob/f48eaae65073d6de1dc44099162b244c362bca2f/src/main/java/duke/Duke.java#L51..L55):

```java

    /**
     * The main method is used to run the program.
     *
     * @param args The command line arguments.
     */

```

Example from [`src/main/java/duke/commands/CommandType.java` lines `48-54`](https://github.com/HugeNoob/ip/blob/f48eaae65073d6de1dc44099162b244c362bca2f/src/main/java/duke/commands/CommandType.java#L48..L54):

```java

    /**
     * The fromString method is used to get the command from the given string.
     *
     * @param value The string representation of the command.
     * @return The command if it exists, null otherwise.
     * @throws DukeInvalidCommandException If the command does not exist.
     */

```

Example from [`src/main/java/duke/tasks/TaskList.java` lines `178-184`](https://github.com/HugeNoob/ip/blob/f48eaae65073d6de1dc44099162b244c362bca2f/src/main/java/duke/tasks/TaskList.java#L178..L184):

```java

    /**
     * Find tasks that contain a specified query in their description.
     *
     * @param query A query specified by the user.
     * @return An ArrayList containing the index of items that contain the specified
     *         query.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by HugeNoob** [comment]
Resolved in 505bbf7
